USE QUANLY_KHO
GO

CREATE TABLE SanPham (
    MaSP INT IDENTITY(1,1) PRIMARY KEY,
    TenSP NVARCHAR(255) NOT NULL,
    MaDanhMuc INT FOREIGN KEY REFERENCES DanhMuc(MaDanhMuc),
    MaNhaCungCap INT FOREIGN KEY REFERENCES NhaCungCap(MaNhaCungCap),
    SoLuongTon INT NOT NULL CHECK (SoLuongTon >= 0),
    GiaNhap DECIMAL(18,2) NOT NULL,
    GiaBan DECIMAL(18,2) NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),
    NgayCapNhat DATETIME DEFAULT GETDATE()
);

CREATE TABLE DanhMuc (
    MaDanhMuc INT IDENTITY(1,1) PRIMARY KEY,
    TenDanhMuc NVARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE NhaCungCap (
    MaNhaCungCap INT IDENTITY(1,1) PRIMARY KEY,
    TenNhaCungCap NVARCHAR(255) NOT NULL,
    TenLienHe NVARCHAR(255),
    SoDienThoai NVARCHAR(20),
    Email NVARCHAR(100) UNIQUE,
    DiaChi NVARCHAR(255)
);
	

CREATE TABLE KhoHang (
    MaKho INT IDENTITY(1,1) PRIMARY KEY,
    TenKho NVARCHAR(255) NOT NULL,
    DiaDiem NVARCHAR(255) NOT NULL
);


CREATE TABLE LichSuNhapXuat (
    MaGiaoDich INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT FOREIGN KEY REFERENCES SanPham(MaSP),
    MaKho INT FOREIGN KEY REFERENCES KhoHang(MaKho),
    LoaiGiaoDich NVARCHAR(50) CHECK (LoaiGiaoDich IN ('Nhập kho', 'Xuất kho')),
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    NgayGiaoDich DATETIME DEFAULT GETDATE(),
    MaNhanVien INT FOREIGN KEY REFERENCES NguoiDung(MaND)
);

CREATE TABLE NguoiDung (
    MaND INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(255) NOT NULL,
    TenDangNhap NVARCHAR(100) NOT NULL UNIQUE,
    MatKhauHash NVARCHAR(255) NOT NULL,
    VaiTro NVARCHAR(50) CHECK (VaiTro IN ('Quản trị', 'Nhân viên')),
    NgayTao DATETIME DEFAULT GETDATE()
);
